### ISSUE TITLE
Unavailable

### ISSUE THREAD

**Issue by gregmichael** [docBliny/ha-mysmartblinds#4] opened 2023-04-21 01:02 UTC
Installed via HACS and I can report that I am seeing my blinds showing up as entities, but I cannot control them: "Unavailable"

**Comment by docBliny** [comment] 2023-06-23 02:46
Closing as duplicate of https://github.com/docBliny/ha-mysmartblinds/issues/3

**Comment by docBliny** [comment] 2023-06-23 02:47
Closing as duplicate of https://github.com/docBliny/ha-mysmartblinds/issues/3

**Closed as completed by docBliny** 2023-06-23 02:47 UTC
