### ISSUE TITLE
Mysmartblinds failing after server update

### ISSUE THREAD

**Issue by SergeantPup** [docBliny/ha-mysmartblinds#3] opened 2023-01-27 18:52 UTC
Hello,

Mysmartblinds servers have been down for a week.  The connection has been re-established via the native app but I think the API info changed.  I'm getting errors in HA `Error logging in or listing devices 400: OIDC conformant clients cannot use /oauth/ro`.  I removed the integration entirely and readded it just in case and all the results are the same so my guess is this needs to be pointed to a different API.

**Comment by docBliny** [comment] 2023-01-27 22:54
Yup, been down for the week too. I got the notification from their support today about the new app version and that things should be back up. Will need to have a look at the new authentication mechanism to see how difficult it might be to get things back up and running. Not sure when I'll have the time at the moment.

**Comment by SergeantPup** [comment] 2023-01-27 22:59
Thank you.  I DID ask them for auth info (just hoping by some miracle they'll just give us the info).  We'll see if I get anything, I've been told no numerous times and I attached those emails to them.

I'm thankful to have base functionality back but this connection is what actually makes the blinds smart.

**Comment by docBliny** [comment] 2023-01-28 05:25
OK, this is theoretically fixed now with https://github.com/docBliny/ha-mysmartblinds/releases/tag/v1.0.3 (and actually in the new forked repo https://github.com/docBliny/smartblinds-client).

However, I can't actually view the status or control anything at the moment because my bridge won't connect (yellow light). Frankly, I'm guessing they haven't got to creating a new firmware version for the bridge so that _it_ uses the new authentication mechanism 😈 

The server will just return an error. You'll see the following in the logs: `Error updating periodic state 502 Server Error: Bad Gateway for url: https://api.mysmartblinds.com/v1/graphql`.

Assuming the bridge magically connects, this might work, but until I get mine connected I can't do anything more, so leaving this issue open.

**Comment by SergeantPup** [comment] 2023-01-28 15:35
Your observations on the firmware align with mine.  On Android it tells me I need an update and constantly ''cant find hub" whereas on IOS it keeps telling me the hub firmware is up to date.  Persistent yellow light as well.

I updated the app and I can confirm I'm now receiving the same error as you in the logs.  Thank you so much!

should 1 or both of us report the yellow light to smartblinds or do you reckon they know?

**Comment by bshep** [comment] 2023-01-28 18:43
> OK, this is theoretically fixed now with https://github.com/docBliny/ha-mysmartblinds/releases/tag/v1.0.3 (and actually in the new forked repo https://github.com/docBliny/smartblinds-client).
> 
> However, I can't actually view the status or control anything at the moment because my bridge won't connect (yellow light). Frankly, I'm guessing they haven't got to creating a new firmware version for the bridge so that _it_ uses the new authentication mechanism 😈
> 
> The server will just return an error. You'll see the following in the logs: `Error updating periodic state 502 Server Error: Bad Gateway for url: https://api.mysmartblinds.com/v1/graphql`.
> 
> Assuming the bridge magically connects, this might work, but until I get mine connected I can't do anything more, so leaving this issue open.

I'm getting the gateway error but I'm not sure why.  I don't think it's a hub connection error.

If I open a console on my docker instance and type in the example program at [this link](https://github.com/docBliny/smartblinds-client/blob/master/example.py) I can get data from the hub, etc so I dont think its a hub issue, seems to be a bug in the integration or some weird interaction within HA

**Comment by docBliny** [comment] 2023-01-28 18:51
> I'm getting the gateway error but I'm not sure why. I don't think it's a hub connection error.
> 
> If I open a console on my docker instance and type in the example program at [this link](https://github.com/docBliny/smartblinds-client/blob/master/example.py) I can get data from the hub, etc so I dont think its a hub issue, seems to be a bug in the integration or some weird interaction within HA

The data you're seeing is coming from the same GraphQL service, so I know that the fix for the authentication works. I see the same error mentioned above trying to get/set state when I snoop my network using the iOS app, so the issue is not limited to this integration.

@bshep Is your hub light yellow? If you go out of Bluetooth range of your blinds are you able to control the blinds via the mobile app?

**Comment by bshep** [comment] 2023-01-29 15:41
> @bshep Is your hub light yellow? If you go out of Bluetooth range of your blinds are you able to control the blinds via the mobile app?

The Hub light was blue until today, i was trying to fix this yesterday and had the blue light all day (rebooted the hub multiple times) when I tried today it turned yellow ( i'm guessing because i was out of bluetooth range? ).  In any case I tried rebooting the hub and I only get the yellow light so I assume I'm now in the same boat as everyone else.

**Comment by docBliny** [comment] 2023-01-31 21:47
Got a response from MSB support today confirming that bridges are currently bricks: `Our developers are working on a fix for the bridge, I'm very sorry that you're still experiencing issues with that.`. So this integration won't work until they fix that (or I find time to finish my own local control bridge alternative, hint hint).

**Comment by bshep** [comment] 2023-02-04 15:10
> (or I find time to finish my own local control bridge alternative, hint hint).

TBH I’ve toyed with the idea of an ESP32 BTLE Bridge to Home Assistant.  The pieces seem to exist already ( there is a project already for direct BTLE control of the blinds, ESPHome has BTLE support, etc ) unfortunately I dont have the expertise to put it all together :’(

I would love to have local control and get rid of their bridge.

**Comment by SergeantPup** [comment] 2023-02-04 15:28
> > (or I find time to finish my own local control bridge alternative, hint hint).
> 
> TBH I’ve toyed with the idea of an ESP32 BTLE Bridge to Home Assistant.  The pieces seem to exist already ( there is a project already for direct BTLE control of the blinds, ESPHome has BTLE support, etc ) unfortunately I dont have the expertise to put it all together :’(
> 
> I would love to have local control and get rid of their bridge. 

When home assistant started supporting Bluetooth, i got a few of the esp boards so hopefully in theory I'd be able to one day aggregate the collection of bt traffic from all the blinds (msb hub barely has the range on a good day).

I was hopeful that somebody more technical than me would figure out how to do it locally with HA new suite of BT tools.

All the cell phones and computers in the house can see the blinds, I just don't have anything to control them.  I have the esp boards and cases, I never got around to flashing them.

As far as trying to control it with a Bluetooth adapter on board with HA, I've had stability issues.  Before there was a recommended list of dangles, I bought the tp link.  When specs came out it said that one was bad.  I bought an asus and it constantly had connection issues and I also had a backup asus and it behaves the same.  The point being, I'm flexible on hardware and ill literally buy whatever it takes as long as I don't have to buy another hub from msb(which last I checked almost doubled in price).

**Comment by docBliny** [comment] 2023-02-04 19:36
@bshep Just to check, have you seen a ESP32 project to control MySmartBlinds, or did you mean just being able to control BTLE in general?

In any case, I'm about 40-50% way through writing a somewhat generic/extensible service to bridge between Bluetooth devices and MQTT. First implementation is obviously for MSB, but I want to add control for our bed, walking desk treadmill, and possibly Ooler (though the existing solution for that has worked well, so probably not worth the time).

However, it'll need a linux-based device to run on, so a Raspberry Pi or similar will be needed. It doesn't leverage any of the Home Assistant Bluetooth (extension) stuff, but since you'll be able to configure it, the idea is that you can drop a Raspberry Pi with different settings around the house and configure specific blinds/other devices that are nearby - I have one blind that's a little further away and the BT connection has never worked correctly for that one with the existing bridge (this solution should also side step the max 7 BT device limitation on most BT adapters; theoretically you should be able to add a second BT adapter USB and run multiple copies on a single RPi if necessary).

**Comment by bshep** [comment] 2023-02-04 20:12
> @bshep Just to check, have you seen a ESP32 project to control MySmartBlinds, or did you mean just being able to control BTLE in general?
> 
> In any case, I'm about 40-50% way through writing a somewhat generic/extensible service to bridge between Bluetooth devices and MQTT. First implementation is obviously for MSB, but I want to add control for our bed, walking desk treadmill, and possibly Ooler (though the existing solution for that has worked well, so probably not worth the time).
> 
> However, it'll need a linux-based device to run on, so a Raspberry Pi or similar will be needed. It doesn't leverage any of the Home Assistant Bluetooth (extension) stuff, but since you'll be able to configure it, the idea is that you can drop a Raspberry Pi with different settings around the house and configure specific blinds/other devices that are nearby - I have one blind that's a little further away and the BT connection has never worked correctly for that one with the existing bridge (this solution should also side step the max 7 BT device limitation on most BT adapters; theoretically you should be able to add a second BT adapter USB and run multiple copies on a single RPi if necessary).

AFAICT There is no library/project for an ESP32 to MySmartBlinds, however there is a python library that can control the blinds using BLE/GATT and porting it to arduino code seems doable.  I was trying in the past to get it working under ESPHome but that is beyond my skill level.

I’m pretty sure i can cook up an arduino sketch to control my blinds, I will try in the next few days, if im successful ill post a gist here and maybe it will be of some use. 

EDIT: here is alink to the python library:

https://github.com/dnschneid/pysmartblinds

EDIT2: I coded a simple BLE scanner for my ESP32, but looks like is an older module and only has BLE 4.2 support and cannot see the blinds, I have some new modules on order and hopefully I can see them with those.

**Comment by bshep** [comment] 2023-02-08 23:20
In case anyone wants to play with some ugly code I made an mysmartblinds to HA bridge using ESP32.

The code is VERY preliminary and likely has many bugs, I don't intend to support it but anyone can use it as they see fit.

You need a newer version of the ESP32's, one that has BT5.0 support ( I have a ESP32-S3 ) and you will need you blind keys from the API.

Code is here:
https://github.com/bshep/MySmartBlindsBridge

**Comment by docBliny** [comment] 2023-02-08 23:25
I also will need beta testers for my new `bt2mqtt` solution soon. I've got most things working, just adding sensors and cleaning up the code... You'll need a linux box to run it (Node app), such as a Raspberry Pi.

Sneak peek:
<img width="1604" alt="image" src="https://user-images.githubusercontent.com/1933511/217676195-81aa0104-2791-475d-ab21-70a733994aa2.png">

**Comment by bshep** [comment] 2023-02-08 23:32
> I also will need beta testers for my new `bt2mqtt` solution soon. I've got most things working, just adding sensors and cleaning up the code... You'll need a linux box to run it (Node app), such as a Raspberry Pi.

I'll be happy to help, I want to see if I can get my bed frame configured as well.  Do you have a solution for sniffing BT traffic as well?

**Comment by docBliny** [comment] 2023-02-08 23:40
> > I also will need beta testers for my new `bt2mqtt` solution soon. I've got most things working, just adding sensors and cleaning up the code... You'll need a linux box to run it (Node app), such as a Raspberry Pi.
> 
> I'll be happy to help, I want to see if I can get my bed frame configured as well. Do you have a solution for sniffing BT traffic as well?

Totally off topic (like most of the discussion here :)) What bed frame do you have? Haven't bothered to sniff BT traffic. It's usually quicker to https://apkpure.com download and http://www.javadecompilers.com/apk ;)

**Comment by bshep** [comment] 2023-02-08 23:46
> > > I also will need beta testers for my new `bt2mqtt` solution soon. I've got most things working, just adding sensors and cleaning up the code... You'll need a linux box to run it (Node app), such as a Raspberry Pi.
> > 
> > 
> > I'll be happy to help, I want to see if I can get my bed frame configured as well. Do you have a solution for sniffing BT traffic as well?
> 
> Totally off topic (like most of the discussion here :)) What bed frame do you have? Haven't bothered to sniff BT traffic. It's usually quicker to https://apkpure.com download and http://www.javadecompilers.com/apk ;)

I have one from purple mattress, they are made by a company called Reverie and their app is terrible.

EDIT: also you're app seem way better designed, mine is mainly a get it working solution.  i also used the apk method :-P

**Comment by SergeantPup** [comment] 2023-02-09 15:53
Blue light suddenly returned on my hub today, no action from me.  I turned off BT and Wifi and I'm able to control blinds.  Same error remains in HA
`This error originated from a custom integration.

Logger: custom_components.mysmartblinds.cover
Source: custom_components/mysmartblinds/cover.py:102
Integration: mysmartblinds (documentation)
First occurred: 10:46:22 AM (4 occurrences)
Last logged: 10:52:13 AM

Error updating periodic state 502 Server Error: Bad Gateway for url: https://api.mysmartblinds.com/v1/graphql`

So I think they fixed their end?  can somebody else confirm?

**Comment by docBliny** [comment] 2023-02-10 00:41
@SergeantPup I also got the blue light today, but it isn't steady (pulses gently). I tried using the mobile app and I'm still unable to control blinds with it via the bridge, so I checked the network traffic - it's still returning errors for their app as well:

<img width="854" alt="image" src="https://user-images.githubusercontent.com/1933511/217971314-a26a7965-b8d2-412f-93e8-a5e18e950393.png">

<img width="853" alt="image" src="https://user-images.githubusercontent.com/1933511/217971939-d5ad3446-a6b6-483f-9509-a547162c45c2.png">

**Comment by bshep** [comment] 2023-02-10 01:28
> Blue light suddenly returned on my hub today, no action from me. I turned off BT and Wifi and I'm able to control blinds. Same error remains in HA `This error originated from a custom integration.
> 
> Logger: custom_components.mysmartblinds.cover Source: custom_components/mysmartblinds/cover.py:102 Integration: mysmartblinds (documentation) First occurred: 10:46:22 AM (4 occurrences) Last logged: 10:52:13 AM
> 
> Error updating periodic state 502 Server Error: Bad Gateway for url: [https://api.mysmartblinds.com/v1/graphql`](https://api.mysmartblinds.com/v1/graphql%60)
> 
> So I think they fixed their end? can somebody else confirm?

I got an email from them about 2 days ago saying they had a solution they were working on and were testing, that they would email me once it was deployed, I havent heard from them so I suspect they are still testing.

**Comment by docBliny** [comment] 2023-02-16 04:09
No update on this repo, but wanted to ask if anyone here is interested in testing the new local solution that connects to the blinds and allows control over MQTT? I have it fairly stable, but I just need to package it up into some deployable format. I'm going to see how well/easy it would be to use as a Docker container, but the alternative is a bunch of files that will require running Node. In any case, a Linux based machine will be required.

**Comment by bshep** [comment] 2023-02-16 20:20
> No update on this repo, but wanted to ask if anyone here is interested in testing the new local solution that connects to the blinds and allows control over MQTT? I have it fairly stable, but I just need to package it up into some deployable format. I'm going to see how well/easy it would be to use as a Docker container, but the alternative is a bunch of files that will require running Node. In any case, a Linux based machine will be required.

I'd be happy to try it, i have a RPI4b and RPI Zero WITH (v1.1) i could test it on both.  I cant promise I will use it long term but def can play with it and try to find any bugs etc.

**Comment by SergeantPup** [comment] 2023-02-17 02:07
> No update on this repo, but wanted to ask if anyone here is interested in testing the new local solution that connects to the blinds and allows control over MQTT? I have it fairly stable, but I just need to package it up into some deployable format. I'm going to see how well/easy it would be to use as a Docker container, but the alternative is a bunch of files that will require running Node. In any case, a Linux based machine will be required.

I took a look at the requirements and I can definitely consume it if you put in docker.  I'm HASS OS on Linux using machine.

I don't have a lot of experience with MQTT besides the Ring integration but I can certainly follow directions.

**Comment by docBliny** [comment] 2023-02-19 22:02
OK, I've uploaded the new application as a Docker image at https://hub.docker.com/r/docbliny/bt2mqtt

I've also made the placeholder repository public at https://github.com/docBliny/bt2mqtt so feel free to move the discussion and open any issues there.

I'll make the code public later (and you can see code in the container in the `/usr/src/app` folder (mainly under `/usr/src/app/services/bt2mqtt/lib`) if you don't like running random code off the internet).

I've tested the Docker image with a Raspberry Pi Zero W (and the directly code on a 3B+), so both of those should work at least.

**Comment by clboles** [comment] 2023-02-24 18:46
Thanks for working on this HA integration.  I, too, plan to move to a local solution as soon as we have a solid option for direct BT control.

In the meantime, all of my blinds are reporting unavailable in HA.  The component was able to query the list of blinds successfully as the entities all show up correctly.  My bridge has a slow blinking blue light, where I think it used to be solid blue.  I have an email into support, but don't have a reply yet.

I'm not seeing any errors in the log, but see these three lines repeating every so often in the log:

```
2023-02-24 13:39:56.766 DEBUG (SyncWorker_7) [custom_components.mysmartblinds.cover] Blind states: {}
2023-02-24 13:39:56.766 DEBUG (SyncWorker_7) [custom_components.mysmartblinds.cover] update_blind_states() took 76.23 seconds
2023-02-24 13:39:56.766 DEBUG (SyncWorker_7) [custom_components.mysmartblinds.cover] _update_periodic() took 76.23 seconds
```

**Comment by SergeantPup** [comment] 2023-06-18 17:13
Hi,  I did some testing today and I turned off bluetooth on phone and iPad and both were able to control the blinds through the hub.  The light blue ring appeared each time a command was sent as expected.  Blinds were perfectly responsive.

What did I do differently?  Not sure but perhaps they fixed their stuff enough on their end where a hard reset and firmware update seemed to fix it.  I uninstalled/reinstalled MSB app from both devices in this timeframe.  iPad appeared to hang up in the checking firmware stage but my android miraculously checked it/connected.  Once the hub was online, iOS has no trouble controlling.

So with that, I think the mysmartblinds part of the problem is resolved and communicating through the bridge.  In this period of time, I moved to Home Assistant Yellow, which means Docker isn't as readily available to me.

At this point I have a question:  Is there something easy we can do to fix the homeassistant version to communicate to the bridge again? and if not, is MQTT going to be the recommended path for this integration?

I'm not saying no to MQTT, I just want to make sure it's going to be worth the extra work and effort or perhaps wait on engaging the MQTT version if we can apply a fix to the hub routing in the original integration.

I haven't been able to pragmatically/voice control my blinds since Jan and I'm looking at a minimum to restore that functionality.

If somebody tells me the MQTT version will be better for the longevity of the integration, I'll trust that and move over to that thread/functionality.

**Comment by docBliny** [comment] 2023-06-23 02:54
This should now be fixed in v1.0.4 (https://github.com/docBliny/ha-mysmartblinds/releases/tag/v1.0.4). There were two issues causing it to still fail, a small typo and a dependency version conflict in the underlying library.

Let me know if it works before I close this issue.

**Comment by clboles** [comment] 2023-06-23 03:26
After updating to 1.0.4, I am able to control my blinds.  Thanks for the update!

The HA Logbook shows the blinds bouncing between unavailable and online every few minutes, so it'll flood the log a bit.  Is that normal behavior in your experience?

**Comment by SergeantPup** [comment] 2023-06-23 03:41
I can control my blinds and boy does it feel good!

Thank you so much.  I put it through several trials and it worked every time.

**Comment by docBliny** [comment] 2023-06-24 15:04
> After updating to 1.0.4, I am able to control my blinds. Thanks for the update!
> 
> The HA Logbook shows the blinds bouncing between unavailable and online every few minutes, so it'll flood the log a bit. Is that normal behavior in your experience?

I'm seeing some dropouts myself, but not every minute. I haven't looked into possible reasons, but I'll poke around at some point since the longest one I've seen was exactly when my blinds were supposed to open this morning.

Closing this issue since the basic functionality has been restored.

<img width="564" alt="image" src="https://github.com/docBliny/ha-mysmartblinds/assets/1933511/c5788706-dbbd-473a-967b-9cc547c5a339">

**Closed as completed by docBliny** 2023-06-24 15:04 UTC
